<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Additional_identity_answer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_additional_identity_answer');
    }

    /*
     * Listing of additional_identity_answer
     */
    function index()
    {
        $data['additional_identity_answer'] = $this->Model_additional_identity_answer->get_all_additional_identity_answer();

        $data['_view'] = 'additional_identity_answer/index';

        $data['title'] = 'Additional identity answer';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/additional_identity_answer/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

}
