<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Biaya_question extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_biaya_question');
        $this->load->model('Model_tipe_bayar');
    }

    /*
     * Listing of biaya_question
     */
    function index()
    {
        $data['biaya_question'] = $this->Model_biaya_question->get_all_biaya_question();

        $data['title'] = 'Biaya question';
        $data['_view'] = 'biaya_question/index';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/biaya_question/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

    public function load($ID_FORM)
    {
        $data['biaya_question'] = $this->Model_biaya_question->get_all_biaya_question_per_form($ID_FORM);
        $data['all_tipe_bayar'] = $this->Model_tipe_bayar->get_all_tipe_bayar();

        $data['title'] = 'Biaya question';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/biaya_question/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

    /*
     * Adding a new biaya_question
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('ID_TIPE_BAYAR','ID TIPE BAYAR','required');
		$this->form_validation->set_rules('ID_FORM','ID FORM','required');
		$this->form_validation->set_rules('QUESTION','QUESTION','required|max_length[1024]');

		if($this->form_validation->run())
        {
            $params = array(
				'ID_TIPE_BAYAR' => $this->input->post('ID_TIPE_BAYAR'),
				'ID_FORM' => $this->input->post('ID_FORM'),
				'QUESTION' => $this->input->post('QUESTION'),
            );

            $biaya_question_id = $this->Model_biaya_question->add_biaya_question($params);
            redirect('biaya_question/load/'.$this->session->currentForm);
        }
        else
        {
			$this->load->model('Model_tipe_bayar');
			$data['all_tipe_bayar'] = $this->Model_tipe_bayar->get_all_tipe_bayar();

			$this->load->model('Model_form');
			$data['all_form'] = $this->Model_form->get_all_form();

            $data['title'] = 'Add biaya question';
            $data['_view'] = 'biaya_question/add';
            $this->load->view('AdminUser/template/header',$data);
            $this->load->view('AdminUser/biaya_question/add',$data);
            $this->load->view('AdminUser/template/footer',$data);
        }
    }

    /*
     * Editing a biaya_question
     */
    function edit($ID_BIAYA_QUESTION)
    {
        // check if the biaya_question exists before trying to edit it
        $data['biaya_question'] = $this->Model_biaya_question->get_biaya_question($ID_BIAYA_QUESTION);

        if(isset($data['biaya_question']['ID_BIAYA_QUESTION']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('ID_TIPE_BAYAR','ID TIPE BAYAR','required');
			$this->form_validation->set_rules('ID_FORM','ID FORM','required');
			$this->form_validation->set_rules('QUESTION','QUESTION','required|max_length[1024]');

			if($this->form_validation->run())
            {
                $params = array(
					'ID_TIPE_BAYAR' => $this->input->post('ID_TIPE_BAYAR'),
					'ID_FORM' => $this->input->post('ID_FORM'),
					'QUESTION' => $this->input->post('QUESTION'),
                );

                $this->Model_biaya_question->update_biaya_question($ID_BIAYA_QUESTION,$params);
                redirect('biaya_question/load/'.$this->session->currentForm);
            }
            else
            {
				$this->load->model('Model_tipe_bayar');
				$data['all_tipe_bayar'] = $this->Model_tipe_bayar->get_all_tipe_bayar();

				$this->load->model('Model_form');
				$data['all_form'] = $this->Model_form->get_all_form();

                $data['title'] = 'edit biaya question';
                $data['_view'] = 'biaya_question/edit';
                $this->load->view('AdminUser/template/header',$data);
                $this->load->view('AdminUser/biaya_question/edit',$data);
                $this->load->view('AdminUser/template/footer',$data);
            }
        }
        else
            show_error('The biaya_question you are trying to edit does not exist.');
    }

    /*
     * Deleting biaya_question
     */
    function remove($ID_BIAYA_QUESTION)
    {
        $biaya_question = $this->Model_biaya_question->get_biaya_question($ID_BIAYA_QUESTION);

        // check if the biaya_question exists before trying to delete it
        if(isset($biaya_question['ID_BIAYA_QUESTION']))
        {
            $this->Model_biaya_question->delete_biaya_question($ID_BIAYA_QUESTION);
            redirect('biaya_question/load/'.$this->session->currentForm);
        }
        else
            show_error('The biaya_question you are trying to delete does not exist.');
    }

}
