<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Identity_answer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_identity_answer');
    }

    /*
     * Listing of identity_answer
     */
    function index()
    {
        $data['identity_answer'] = $this->Model_identity_answer->get_all_identity_answer();

        $data['_view'] = 'identity_answer/index';
        $data['title'] = 'Identity answer';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/identity_answer/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

}
