<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Identity_option extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_identity_option');
    }

    /*
     * Listing of identity_option
     */
    function index()
    {
        $data['identity_option'] = $this->Model_identity_option->get_all_identity_option();

        $data['title'] = 'Identity option';
        $data['_view'] = 'identity_option/index';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/identity_option/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

    /*
     * Adding a new identity_option
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'ID_IDENTITY_QUESTION' => $this->input->post('ID_IDENTITY_QUESTION'),
				'ID_INPUT_TYPE' => $this->input->post('ID_INPUT_TYPE'),
				'OPTION' => $this->input->post('OPTION'),
            );

            $identity_option_id = $this->Model_identity_option->add_identity_option($params);
            redirect('identity_option/index');
        }
        else
        {
            $data['title'] = 'Add identity option';
            $data['_view'] = 'identity_option/add';

            $this->load->view('AdminUser/template/header',$data);
            $this->load->view('AdminUser/identity_option/add',$data);
            $this->load->view('AdminUser/template/footer',$data);
        }
    }

    /*
     * Editing a identity_option
     */
    function edit($ID_IDENTITY_OPTION)
    {
        // check if the identity_option exists before trying to edit it
        $data['identity_option'] = $this->Model_identity_option->get_identity_option($ID_IDENTITY_OPTION);

        if(isset($data['identity_option']['ID_IDENTITY_OPTION']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'ID_IDENTITY_QUESTION' => $this->input->post('ID_IDENTITY_QUESTION'),
					'ID_INPUT_TYPE' => $this->input->post('ID_INPUT_TYPE'),
					'OPTION' => $this->input->post('OPTION'),
                );

                $this->Model_identity_option->update_identity_option($ID_IDENTITY_OPTION,$params);
                redirect('identity_option/index');
            }
            else
            {
                $data['title'] = 'Edit identity option';
                $data['_view'] = 'identity_option/edit';

                $this->load->view('AdminUser/template/header',$data);
                $this->load->view('AdminUser/identity_option/edit',$data);
                $this->load->view('AdminUser/template/footer',$data);
            }
        }
        else
            show_error('The identity_option you are trying to edit does not exist.');
    }

    /*
     * Deleting identity_option
     */
    function remove($ID_IDENTITY_OPTION)
    {
        $identity_option = $this->Model_identity_option->get_identity_option($ID_IDENTITY_OPTION);

        // check if the identity_option exists before trying to delete it
        if(isset($identity_option['ID_IDENTITY_OPTION']))
        {
            $this->Model_identity_option->delete_identity_option($ID_IDENTITY_OPTION);
            redirect('identity_option/index');
        }
        else
            show_error('The identity_option you are trying to delete does not exist.');
    }

}
