<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Place_category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_place_category');
    }

    /*
     * Listing of place_category
     */
    function index()
    {
        $data['place_category'] = $this->Model_place_category->get_all_place_category();

        $data['_view'] = 'place_category/index';
        $this->load->view('SuperAdmin/place_category/index',$data);
    }

    /*
     * Adding a new place_category
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('CATEGORY','CATEGORY','required|max_length[255]');

		if($this->form_validation->run())
        {
            $params = array(
				'CATEGORY' => $this->input->post('CATEGORY'),
            );

            $place_category_id = $this->Model_place_category->add_place_category($params);
            redirect('place_category/index');
        }
        else
        {
            $data['_view'] = 'place_category/add';
            $this->load->view('SuperAdmin/place_category/add',$data);
        }
    }

    /*
     * Editing a place_category
     */
    function edit($ID_PLACE_CATEGORY)
    {
        // check if the place_category exists before trying to edit it
        $data['place_category'] = $this->Model_place_category->get_place_category($ID_PLACE_CATEGORY);

        if(isset($data['place_category']['ID_PLACE_CATEGORY']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('CATEGORY','CATEGORY','required|max_length[255]');

			if($this->form_validation->run())
            {
                $params = array(
					'CATEGORY' => $this->input->post('CATEGORY'),
                );

                $this->Model_place_category->update_place_category($ID_PLACE_CATEGORY,$params);
                redirect('place_category/index');
            }
            else
            {
                $data['_view'] = 'place_category/edit';
                $this->load->view('SuperAdmin/place_category/edit',$data);
            }
        }
        else
            show_error('The place_category you are trying to edit does not exist.');
    }

    /*
     * Deleting place_category
     */
    function remove($ID_PLACE_CATEGORY)
    {
        $place_category = $this->Model_place_category->get_place_category($ID_PLACE_CATEGORY);

        // check if the place_category exists before trying to delete it
        if(isset($place_category['ID_PLACE_CATEGORY']))
        {
            $this->Model_place_category->delete_place_category($ID_PLACE_CATEGORY);
            redirect('place_category/index');
        }
        else
            show_error('The place_category you are trying to delete does not exist.');
    }

}
