<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Place_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_place_type');
        $this->logged_in();
    }

    private function logged_in() {
        if(! $this->session->userdata('authenticated')) {
            redirect(site_url('SuperAdmin/login'));
        }
    }
    /*
     * Listing of place_type
     */
    function index()
    {
        $data['place_type'] = $this->Model_place_type->get_all_place_type();

        $data['title'] = 'Place Type';
        $data['_view'] = 'place_type/index';
        $this->load->view('SuperAdmin/template/header',$data);
        $this->load->view('SuperAdmin/place_type/index',$data);
        $this->load->view('SuperAdmin/template/footer',$data);
    }

    /*
     * Adding a new place_type
     */
    function add()
    {
        $this->load->library('form_validation');

    		$this->form_validation->set_rules('TYPE','TYPE','required|max_length[255]');

    		if($this->form_validation->run())
            {
                $params = array(
    				'TYPE' => $this->input->post('TYPE'),
                );

            $place_type_id = $this->Model_place_type->add_place_type($params);
            redirect(site_url('Place_type/index'));
        }
        else
        {
            $data['title'] = 'Add Place Type';
            $data['_view'] = 'place_type/add';
            $this->load->view('SuperAdmin/template/header',$data);
            $this->load->view('SuperAdmin/place_type/add',$data);
            $this->load->view('SuperAdmin/template/footer',$data);
        }
    }

    /*
     * Editing a place_type
     */
    function edit($ID_PLACE_TYPE)
    {
        // check if the place_type exists before trying to edit it
        $data['place_type'] = $this->Model_place_type->get_place_type($ID_PLACE_TYPE);

        if(isset($data['place_type']['ID_PLACE_TYPE']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('TYPE','TYPE','required|max_length[255]');

			if($this->form_validation->run())
            {
                $params = array(
					'TYPE' => $this->input->post('TYPE'),
                );

                $this->Model_place_type->update_place_type($ID_PLACE_TYPE,$params);
                redirect(site_url('Place_type/index'));
            }
            else
            {
                $data['title'] = 'Edit Place Type';
                $data['_view'] = 'place_type/edit';
                $this->load->view('SuperAdmin/template/header',$data);
                $this->load->view('SuperAdmin/place_type/edit',$data);
                $this->load->view('SuperAdmin/template/footer',$data);
            }
        }
        else
            show_error('The place_type you are trying to edit does not exist.');
    }

    /*
     * Deleting place_type
     */
    function remove($ID_PLACE_TYPE)
    {
        $place_type = $this->Model_place_type->get_place_type($ID_PLACE_TYPE);

        // check if the place_type exists before trying to delete it
        if(isset($place_type['ID_PLACE_TYPE']))
        {
            $this->Model_place_type->delete_place_type($ID_PLACE_TYPE);
            redirect(site_url('place_type/index'));
        }
        else
            show_error('The place_type you are trying to delete does not exist.');
    }

}
