<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Submit extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_submit');
    }

    /*
     * Listing of submit
     */
    function index()
    {
        $data['submit'] = $this->Model_submit->get_all_submit();

        $data['_view'] = 'submit/index';
        $data['title'] = 'Submit';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/submit/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }

}
