<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tkm_answer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_tkm_answer');
    }

    /*
     * Listing of tkm_answer
     */
    function index()
    {
        $data['tkm_answer'] = $this->Model_tkm_answer->get_all_tkm_answer();

        $data['_view'] = 'tkm_answer/index';
        $data['title'] = 'TKM answer';

        $this->load->view('AdminUser/template/header',$data);
        $this->load->view('AdminUser/tkm_answer/index',$data);
        $this->load->view('AdminUser/template/footer',$data);
    }
    
}
