<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_additional_identity_option extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get additional_identity_option by ID_ADDITIONAL_IDENTITY_OPTION
     */
    function get_additional_identity_option($ID_ADDITIONAL_IDENTITY_OPTION)
    {
        return $this->db->get_where('ADDITIONAL_IDENTITY_OPTION',array('ID_ADDITIONAL_IDENTITY_OPTION'=>$ID_ADDITIONAL_IDENTITY_OPTION))->row_array();
    }

    /*
     * Get all additional_identity_option
     */
    function get_all_additional_identity_option()
    {
        $this->db->order_by('ID_ADDITIONAL_IDENTITY_OPTION', 'asc');
        return $this->db->get('ADDITIONAL_IDENTITY_OPTION')->result_array();
    }

    function get_all_additional_identity_option_per_id($ID_ADDITIONAL_IDENTITY_OPTION)
    {
        $this->db->where('ID_ADDITIONAL_IDENTITY_QUESTION',	$ID_ADDITIONAL_IDENTITY_OPTION);
        $this->db->order_by('ID_ADDITIONAL_IDENTITY_OPTION', 'asc');
        return $this->db->get('ADDITIONAL_IDENTITY_OPTION')->result_array();
    }
    /*
     * function to add new additional_identity_option
     */
    function add_additional_identity_option($params)
    {
        $this->db->insert('ADDITIONAL_IDENTITY_OPTION',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update additional_identity_option
     */
    function update_additional_identity_option($ID_ADDITIONAL_IDENTITY_OPTION,$params)
    {
        $this->db->where('ID_ADDITIONAL_IDENTITY_OPTION',$ID_ADDITIONAL_IDENTITY_OPTION);
        return $this->db->update('ADDITIONAL_IDENTITY_OPTION',$params);
    }

    /*
     * function to delete additional_identity_option
     */
    function delete_additional_identity_option($ID_ADDITIONAL_IDENTITY_OPTION)
    {
        return $this->db->delete('ADDITIONAL_IDENTITY_OPTION',array('ID_ADDITIONAL_IDENTITY_OPTION'=>$ID_ADDITIONAL_IDENTITY_OPTION));
    }
}
