<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_tkm_question extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tkm_question by ID_TKM_QUESTION
     */
    function get_tkm_question($ID_TKM_QUESTION)
    {
        return $this->db->get_where('TKM_QUESTION',array('ID_TKM_QUESTION'=>$ID_TKM_QUESTION))->row_array();
    }
        
    /*
     * Get all tkm_question
     */
    function get_all_tkm_question()
    {
        $this->db->order_by('ID_TKM_QUESTION', 'desc');
        return $this->db->get('TKM_QUESTION')->result_array();
    }
        
    /*
     * function to add new tkm_question
     */
    function add_tkm_question($params)
    {
        $this->db->insert('TKM_QUESTION',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tkm_question
     */
    function update_tkm_question($ID_TKM_QUESTION,$params)
    {
        $this->db->where('ID_TKM_QUESTION',$ID_TKM_QUESTION);
        return $this->db->update('TKM_QUESTION',$params);
    }
    
    /*
     * function to delete tkm_question
     */
    function delete_tkm_question($ID_TKM_QUESTION)
    {
        return $this->db->delete('TKM_QUESTION',array('ID_TKM_QUESTION'=>$ID_TKM_QUESTION));
    }
}
