<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_admin extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by ID_ADMIN
     */
    function get_admin($ID_ADMIN)
    {
        return $this->db->get_where('ADMIN',array('ID_ADMIN'=>$ID_ADMIN))->row_array();
    }
        
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        $this->db->order_by('ID_ADMIN', 'desc');
        return $this->db->get('ADMIN')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('ADMIN',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($ID_ADMIN,$params)
    {
        $this->db->where('ID_ADMIN',$ID_ADMIN);
        return $this->db->update('ADMIN',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($ID_ADMIN)
    {
        return $this->db->delete('ADMIN',array('ID_ADMIN'=>$ID_ADMIN));
    }
}
