<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_tkm_answer extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tkm_answer by ID_TKM_ANSWER
     */
    function get_tkm_answer($ID_TKM_ANSWER)
    {
        return $this->db->get_where('TKM_ANSWER',array('ID_TKM_ANSWER'=>$ID_TKM_ANSWER))->row_array();
    }

    /*
     * Get all tkm_answer
     */
    function get_all_tkm_answer()
    {
        $this->db->order_by('ID_TKM_ANSWER', 'desc');
        return $this->db->get('TKM_ANSWER')->result_array();
    }

    function get_tkm_answer_persubmit($idSubmit){
      $answer = $this->db->select('t.ID_TKM_ANSWER,t.ID_SUBMIT, t.VALUE ,t.PRIORITY, tq.QUESTION' )
            ->from('TKM_ANSWER AS t, TKM AS tq')
            ->where('t.ID_TKM = tq.ID_TKM')
            ->where('t.ID_SUBMIT',$idSubmit);
      $answer = $this->db->get();

      return $answer;

        //return $this->db->get_where('TKM_ANSWER',array('ID_SUBMIT'=>$idSubmit));
    }
    /*
     * function to add new tkm_answer
     */
    function add_tkm_answer($params)
    {
        $this->db->insert('TKM_ANSWER',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update tkm_answer
     */
    function update_tkm_answer($ID_TKM_ANSWER,$params)
    {
        $this->db->where('ID_TKM_ANSWER',$ID_TKM_ANSWER);
        return $this->db->update('TKM_ANSWER',$params);
    }

    /*
     * function to delete tkm_answer
     */
    function delete_tkm_answer($ID_TKM_ANSWER)
    {
        return $this->db->delete('TKM_ANSWER',array('ID_TKM_ANSWER'=>$ID_TKM_ANSWER));
    }
}
