<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_biaya_question extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get biaya_question by ID_BIAYA_QUESTION
     */
    function get_biaya_question($ID_BIAYA_QUESTION)
    {
        return $this->db->get_where('BIAYA_QUESTION',array('ID_BIAYA_QUESTION'=>$ID_BIAYA_QUESTION))->row_array();
    }

    /*
     * Get all biaya_question
     */
    function get_all_biaya_question()
    {
        $this->db->order_by('ID_BIAYA_QUESTION', 'desc');
        return $this->db->get('BIAYA_QUESTION')->result_array();
    }

    /*
     * function to add new biaya_question
     */
    function add_biaya_question($params)
    {
        $this->db->insert('BIAYA_QUESTION',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update biaya_question
     */
    function update_biaya_question($ID_BIAYA_QUESTION,$params)
    {
        $this->db->where('ID_BIAYA_QUESTION',$ID_BIAYA_QUESTION);
        return $this->db->update('BIAYA_QUESTION',$params);
    }

    /*
     * function to delete biaya_question
     */
    function delete_biaya_question($ID_BIAYA_QUESTION)
    {
        return $this->db->delete('BIAYA_QUESTION',array('ID_BIAYA_QUESTION'=>$ID_BIAYA_QUESTION));
    }

    public function countlistQuestion($idForm,$tipeBayar)
    {
        $this->db->where('ID_FORM',$idForm);
        $this->db->where('ID_TIPE_BAYAR',$tipeBayar);
        $this->db->from("BIAYA_QUESTION");
        $count = $this->db->count_all_results();
        return $count;
    }

    public function listQuestion($idForm,$tipeBayar)
    {
        $this->db->where('ID_FORM',$idForm);
        $this->db->where('ID_TIPE_BAYAR',$tipeBayar);
        $this->db->from("BIAYA_QUESTION");
        $question = $this->db->get();
        return $question;
    }
}
