<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_place_category extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get place_category by ID_PLACE_CATEGORY
     */
    function get_place_category($ID_PLACE_CATEGORY)
    {
        return $this->db->get_where('PLACE_CATEGORY',array('ID_PLACE_CATEGORY'=>$ID_PLACE_CATEGORY))->row_array();
    }
        
    /*
     * Get all place_category
     */
    function get_all_place_category()
    {
        $this->db->order_by('ID_PLACE_CATEGORY', 'desc');
        return $this->db->get('PLACE_CATEGORY')->result_array();
    }
        
    /*
     * function to add new place_category
     */
    function add_place_category($params)
    {
        $this->db->insert('PLACE_CATEGORY',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update place_category
     */
    function update_place_category($ID_PLACE_CATEGORY,$params)
    {
        $this->db->where('ID_PLACE_CATEGORY',$ID_PLACE_CATEGORY);
        return $this->db->update('PLACE_CATEGORY',$params);
    }
    
    /*
     * function to delete place_category
     */
    function delete_place_category($ID_PLACE_CATEGORY)
    {
        return $this->db->delete('PLACE_CATEGORY',array('ID_PLACE_CATEGORY'=>$ID_PLACE_CATEGORY));
    }
}
