<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_identity_option extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get identity_option by ID_IDENTITY_OPTION
     */
    function get_identity_option($ID_IDENTITY_OPTION)
    {
        return $this->db->get_where('IDENTITY_OPTION',array('ID_IDENTITY_OPTION'=>$ID_IDENTITY_OPTION))->row_array();
    }
        
    /*
     * Get all identity_option
     */
    function get_all_identity_option()
    {
        $this->db->order_by('ID_IDENTITY_OPTION', 'desc');
        return $this->db->get('IDENTITY_OPTION')->result_array();
    }
        
    /*
     * function to add new identity_option
     */
    function add_identity_option($params)
    {
        $this->db->insert('IDENTITY_OPTION',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update identity_option
     */
    function update_identity_option($ID_IDENTITY_OPTION,$params)
    {
        $this->db->where('ID_IDENTITY_OPTION',$ID_IDENTITY_OPTION);
        return $this->db->update('IDENTITY_OPTION',$params);
    }
    
    /*
     * function to delete identity_option
     */
    function delete_identity_option($ID_IDENTITY_OPTION)
    {
        return $this->db->delete('IDENTITY_OPTION',array('ID_IDENTITY_OPTION'=>$ID_IDENTITY_OPTION));
    }
}
