<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_tipe_bayar extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipe_bayar by ID_TYPE_BAYAR
     */
    function get_tipe_bayar($ID_TYPE_BAYAR)
    {
        return $this->db->get_where('TIPE_BAYAR',array('ID_TYPE_BAYAR'=>$ID_TYPE_BAYAR))->row_array();
    }
        
    /*
     * Get all tipe_bayar
     */
    function get_all_tipe_bayar()
    {
        $this->db->order_by('ID_TYPE_BAYAR', 'desc');
        return $this->db->get('TIPE_BAYAR')->result_array();
    }
        
    /*
     * function to add new tipe_bayar
     */
    function add_tipe_bayar($params)
    {
        $this->db->insert('TIPE_BAYAR',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipe_bayar
     */
    function update_tipe_bayar($ID_TYPE_BAYAR,$params)
    {
        $this->db->where('ID_TYPE_BAYAR',$ID_TYPE_BAYAR);
        return $this->db->update('TIPE_BAYAR',$params);
    }
    
    /*
     * function to delete tipe_bayar
     */
    function delete_tipe_bayar($ID_TYPE_BAYAR)
    {
        return $this->db->delete('TIPE_BAYAR',array('ID_TYPE_BAYAR'=>$ID_TYPE_BAYAR));
    }
}
