<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_priority extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get priority by ID_PRIORITY
     */
    function get_priority($ID_PRIORITY)
    {
        return $this->db->get_where('PRIORITY',array('ID_PRIORITY'=>$ID_PRIORITY))->row_array();
    }

    /*
     * Get all priority
     */
    function get_all_priority()
    {
        $this->db->order_by('ID_PRIORITY', 'desc');
        return $this->db->get('PRIORITY')->result_array();
    }

    /*
     * function to add new priority
     */
    function add_priority($params)
    {
        $this->db->insert('PRIORITY',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update priority
     */
    function update_priority($ID_PRIORITY,$params)
    {
        $this->db->where('ID_PRIORITY',$ID_PRIORITY);
        return $this->db->update('PRIORITY',$params);
    }

    /*
     * function to delete priority
     */
    function delete_priority($ID_PRIORITY)
    {
        return $this->db->delete('PRIORITY',array('ID_PRIORITY'=>$ID_PRIORITY));
    }
}
