<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_input_type extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get input_type by ID_INPUT_TYPE
     */
    function get_input_type($ID_INPUT_TYPE)
    {
        return $this->db->get_where('INPUT_TYPE',array('ID_INPUT_TYPE'=>$ID_INPUT_TYPE))->row_array();
    }
        
    /*
     * Get all input_type
     */
    function get_all_input_type()
    {
        $this->db->order_by('ID_INPUT_TYPE', 'desc');
        return $this->db->get('INPUT_TYPE')->result_array();
    }
        
    /*
     * function to add new input_type
     */
    function add_input_type($params)
    {
        $this->db->insert('INPUT_TYPE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update input_type
     */
    function update_input_type($ID_INPUT_TYPE,$params)
    {
        $this->db->where('ID_INPUT_TYPE',$ID_INPUT_TYPE);
        return $this->db->update('INPUT_TYPE',$params);
    }
    
    /*
     * function to delete input_type
     */
    function delete_input_type($ID_INPUT_TYPE)
    {
        return $this->db->delete('INPUT_TYPE',array('ID_INPUT_TYPE'=>$ID_INPUT_TYPE));
    }
}
