<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_form_detail extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get form_detail by ID
     */
    function get_form_detail($ID)
    {
        return $this->db->get_where('FORM_DETAIL',array('ID'=>$ID))->row_array();
    }

    /*
     * Get all form_detail
     */
    function get_all_form_detail()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('FORM_DETAIL')->result_array();
    }

    function get_form_detail_persubmit($idSubmit){
      return $this->db->get_where('FORM_DETAIL',array('ID_SUBMIT'=>$idSubmit));
    }
    /*
     * function to add new form_detail
     */
    function add_form_detail($params)
    {
        $this->db->insert('FORM_DETAIL',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update form_detail
     */
    function update_form_detail($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('FORM_DETAIL',$params);
    }

    /*
     * function to delete form_detail
     */
    function delete_form_detail($ID)
    {
        return $this->db->delete('FORM_DETAIL',array('ID'=>$ID));
    }
}
