<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_tkm extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tkm by ID_TKM
     */
    function get_tkm($ID_TKM)
    {
        return $this->db->get_where('TKM',array('ID_TKM'=>$ID_TKM))->row_array();
    }
        
    /*
     * Get all tkm
     */
    function get_all_tkm()
    {
        $this->db->order_by('ID_TKM', 'desc');
        return $this->db->get('TKM')->result_array();
    }
        
    /*
     * function to add new tkm
     */
    function add_tkm($params)
    {
        $this->db->insert('TKM',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tkm
     */
    function update_tkm($ID_TKM,$params)
    {
        $this->db->where('ID_TKM',$ID_TKM);
        return $this->db->update('TKM',$params);
    }
    
    /*
     * function to delete tkm
     */
    function delete_tkm($ID_TKM)
    {
        return $this->db->delete('TKM',array('ID_TKM'=>$ID_TKM));
    }
}
